#pragma once

#include <AppSpecsJSI.h>  // generated by RN codegen from src/specs/NativeAudioEngine.ts

#include <memory>

namespace facebook::react {

/**
 * NativeAudioEngine — pure C++ TurboModule.
 *
 * Subclasses the codegen CRTP base so JS calls dispatch SYNCHRONOUSLY into these
 * C++ methods via JSI (no JNI, no async bridge). Each method just forwards to the
 * AudioEngine singleton, which enqueues a lock-free event for the audio thread.
 *
 * Registered in jni/OnLoad.cpp via cxxModuleProvider().
 */
class NativeAudioEngine
    : public NativeAudioEngineCxxSpec<NativeAudioEngine> {
 public:
  explicit NativeAudioEngine(std::shared_ptr<CallInvoker> jsInvoker);

  // Numbers arrive from JS as double; we narrow at the boundary.
  void noteOn(jsi::Runtime& rt, double pitch, double velocity);
  void noteOff(jsi::Runtime& rt, double pitch);
  void setMasterGain(jsi::Runtime& rt, double gain);
  void setProgram(jsi::Runtime& rt, double preset);
  void setSustain(jsi::Runtime& rt, bool on);
};

} // namespace facebook::react
